OrdererOrgs:
  - Name: OrderingService
    Domain: food-network.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Importer
    Domain: importer.food-network.com
    EnableNodeOUs: true
    Template:
      Count: 2

    Users: 
      Count: 1
  - Name: Distributor
    Domain: distributor.food-network.com
    EnableNodeOUs: true
    Template:
      Count: 2

    Users: 
      Count: 1
  - Name: Customer
    Domain: customer.food-network.com
    EnableNodeOUs: true
    Template:
      Count: 2

    Users:
      Count: 1
